spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sungboktime?serverTimezone=Asia/Seoul
    username: ${MYSQL_ID}
    password: ${MYSQL_PW}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    com.sungbok.lol.sungboktime.service.MemberService: DEBUG
    root: INFO


riot:
  api-key: ${RIOT_API_KEY}
  account-base-url: https://asia.api.riotgames.com
  league-base-url: https://kr.api.riotgames.com


